language: rust
sudo: false
matrix:
  # Run only on nightly now as neither stable nor beta support benchmark tests.
  fast_finish: true
  include:
    - env: TARGET=x86_64-apple-darwin CC=clang CXX=clang++
      os: osx
      rust: nightly
      before_install:
        - brew update
        - brew install libsodium

    - env: TARGET=x86_64-unknown-linux-gnu CC=gcc-5 CXX=g++-5
      os: linux
      rust: nightly
      addons:
        apt:
          packages:
            - g++-5
            - gcc-5
            - libsodium13
          sources:
            - ubuntu-toolchain-r-test

script:
  # We don't run `cargo bench` because Travis CI isn't a reliable platform for
  # measuring performance. We run `cargo test` to ensure that changes do not
  # break the build.
  - $CC --version
  - $CXX --version
  - ./cargo_all test --release --target=$TARGET --verbose
